export const GAME_MODES = {
  PLAYER_VS_NPC: "PLAYER_VS_NPC",
  PLAYER_VS_PLAYER: "PLAYER_VS_PLAYER"
};

export const DEFAULT_GAME_MODE = GAME_MODES.PLAYER_VS_PLAYER;

export const FREE_PLAY_MODES = {
  PLAYER_VS_PLAYER: "PVP",
  PLAYER_VS_CPU_EASY: "PVCPU_EASY",
  PLAYER_VS_CPU_TACTICAL: "PVCPU_TACTICAL"
};

export const DEFAULT_FREE_PLAY_MODE = FREE_PLAY_MODES.PLAYER_VS_PLAYER;
